package paloalto

var colorMap = map[string]string{
	"color1":  "赤",
	"color2":  "緑",
	"color3":  "青",
	"color4":  "黄色",
	"color5":  "赤胴色",
	"color6":  "オレンジ",
	"color7":  "紫",
	"color8":  "灰色",
	"color9":  "ライト グリーン",
	"color10": "シアン",
	"color11": "ライト グレー",
	"color12": "青灰色",
	"color13": "ライム",
	"color14": "黒",
	"color15": "金色",
	"color16": "茶色",
	"color17": "オリーブ",
	"color19": "マルーン",
	"color20": "レッド オレンジ",
	"color21": "イエロー オレンジ",
	"color22": "フォレスト グリーン",
	"color23": "ターコイズ ブルー",
	"color24": "Azure Instrumentation Key",
	"color25": "空色",
	"color26": "ミッドナイト ブルー",
	"color27": "ミディアム ブルー",
	"color28": "コバルト ブルー",
	"color29": "バイオレット ブルー",
	"color30": "ブルー バイオレット",
	"color31": "ミディアム バイオレット",
	"color32": "ミディアム ローズ",
	"color33": "ラベンダー",
	"color34": "オーキッド",
	"color35": "Thistle",
	"color36": "ピーチ",
	"color37": "サーモン",
	"color38": "マゼンタ",
	"color39": "レッド バイオレット",
	"color40": "マホガニー",
	"color41": "バーント シェンナ",
	"color42": "栗色",
}

/*
var colorMap = map[string]string{
	"color1":  "赤",
	"color2":  "緑",
	"color3":  "青",
	"color4":  "黄色",
	"color5":  "紫",
	"color6":  "オレンジ",
	"color7":  "シアン",
	"color8":  "マゼンタ",
	"color9":  "ライム",
	"color10": "ピンク",
	"color11": "ティール",
	"color12": "ラベンダー",
	"color13": "茶色",
	"color14": "ベージュ",
	"color15": "栗色",
	"color16": "ミント",
	"color17": "オリーブ",
	"color18": "コーラル",
	"color19": "ネイビー",
	"color20": "灰色",
	"color21": "白",
	"color22": "黒",
	"color23": "金",
	"color24": "銀",
	"color25": "銅",
	"color26": "ピーチ",
	"color27": "サーモン",
	"color28": "ターコイズ",
	"color29": "バイオレット",
	"color30": "インディゴ",
	"color31": "アンバー",
	"color32": "黄緑",
	"color33": "アクアマリン",
	"color34": "クリムゾン",
	"color35": "カーキ",
	"color36": "プラム",
	"color37": "オーキッド",
	"color38": "アズール",
	"color39": "ローズ",
	"color40": "サフラン",
	"color41": "エメラルド",
	"color42": "ルビー",
}
*/
