// Code generated by "stringer -type OutType -trimprefix OutType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutTypeUnknown-0]
	_ = x[OutTypeExcel-1]
	_ = x[OutTypeJson-2]
	_ = x[OutTypeCsv-3]
}

const _OutType_name = "UnknownExcelJsonCsv"

var _OutType_index = [...]uint8{0, 7, 12, 16, 19}

func (i OutType) String() string {
	if i < 0 || i >= OutType(len(_OutType_index)-1) {
		return "OutType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutType_name[_OutType_index[i]:_OutType_index[i+1]]
}
